SET DEFINE OFF;
SET SERVEROUTPUT ON;
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

BEGIN EXECUTE IMMEDIATE 'DROP TABLE AUDIT_LOGS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CARE_RECOMMENDATIONS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RECOVERY_MONITORING CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TREATMENTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE READMISSION_PREDICTIONS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MEDICAL_HISTORIES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PATIENTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DATASET_METRICS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE AI_MODELS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE HOSPITAL_ANALYTICS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE USERS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE USER_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE PATIENT_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE HISTORY_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE PREDICTION_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE TREATMENT_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE RECOVERY_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE RECOMMENDATION_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE MODEL_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE METRIC_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ANALYTICS_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE AUDIT_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- CREATE SEQUENCES
CREATE SEQUENCE USER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PATIENT_SEQ START WITH 1001 INCREMENT BY 1;
CREATE SEQUENCE HISTORY_SEQ START WITH 5001 INCREMENT BY 1;
CREATE SEQUENCE PREDICTION_SEQ START WITH 8001 INCREMENT BY 1;
CREATE SEQUENCE TREATMENT_SEQ START WITH 3001 INCREMENT BY 1;
CREATE SEQUENCE RECOVERY_SEQ START WITH 4001 INCREMENT BY 1;
CREATE SEQUENCE RECOMMENDATION_SEQ START WITH 2001 INCREMENT BY 1;
CREATE SEQUENCE MODEL_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE METRIC_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ANALYTICS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE AUDIT_SEQ START WITH 1 INCREMENT BY 1;

-- CREATE TABLES

CREATE TABLE USERS (
    USER_ID NUMBER PRIMARY KEY,
    FULL_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    HASHED_PASSWORD VARCHAR2(255) NOT NULL,
    ROLE VARCHAR2(50) NOT NULL,
    DEPARTMENT VARCHAR2(100),
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PATIENTS (
    PATIENT_ID NUMBER PRIMARY KEY,
    MEDICAL_RECORD_NUMBER VARCHAR2(50) UNIQUE NOT NULL,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,
    GENDER VARCHAR2(20),
    AGE_GROUP VARCHAR2(20),
    RACE VARCHAR2(50),
    BLOOD_TYPE VARCHAR2(10),
    CONTACT_NUMBER VARCHAR2(30),
    PRIMARY_DOCTOR_ID NUMBER REFERENCES USERS(USER_ID),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE MEDICAL_HISTORIES (
    HISTORY_ID NUMBER PRIMARY KEY,
    PATIENT_ID NUMBER NOT NULL REFERENCES PATIENTS(PATIENT_ID) ON DELETE CASCADE,
    PRIMARY_DIAGNOSIS VARCHAR2(255),
    SECONDARY_DIAGNOSIS VARCHAR2(255),
    ADDITIONAL_DIAGNOSIS VARCHAR2(255),
    COMORBIDITIES_COUNT NUMBER DEFAULT 0,
    ADMISSION_TYPE VARCHAR2(50),
    NUM_LAB_PROCEDURES NUMBER DEFAULT 0,
    NUM_PROCEDURES NUMBER DEFAULT 0,
    NUM_MEDICATIONS NUMBER DEFAULT 0,
    NUMBER_OUTPATIENT NUMBER DEFAULT 0,
    NUMBER_EMERGENCY NUMBER DEFAULT 0,
    NUMBER_INPATIENT NUMBER DEFAULT 0,
    TIME_IN_HOSPITAL NUMBER DEFAULT 1,
    ADMISSION_DATE DATE,
    DISCHARGE_DATE DATE
);

CREATE TABLE READMISSION_PREDICTIONS (
    PREDICTION_ID NUMBER PRIMARY KEY,
    PATIENT_ID NUMBER NOT NULL REFERENCES PATIENTS(PATIENT_ID) ON DELETE CASCADE,
    MODEL_NAME VARCHAR2(50) NOT NULL,
    READMISSION_RISK_SCORE NUMBER(6,4) NOT NULL,
    RISK_CATEGORY VARCHAR2(20) NOT NULL,
    PREDICTED_READMIT_30D NUMBER(1) NOT NULL,
    CONFIDENCE_INTERVAL VARCHAR2(50),
    PREDICTION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TREATMENTS (
    TREATMENT_ID NUMBER PRIMARY KEY,
    PATIENT_ID NUMBER NOT NULL REFERENCES PATIENTS(PATIENT_ID) ON DELETE CASCADE,
    MEDICATION_NAME VARCHAR2(100) NOT NULL,
    DOSAGE VARCHAR2(50),
    FREQUENCY VARCHAR2(50),
    START_DATE DATE,
    END_DATE DATE,
    EFFECTIVENESS_SCORE NUMBER(5,2),
    STATUS VARCHAR2(30) DEFAULT 'ACTIVE'
);

CREATE TABLE RECOVERY_MONITORING (
    OUTCOME_ID NUMBER PRIMARY KEY,
    PATIENT_ID NUMBER NOT NULL REFERENCES PATIENTS(PATIENT_ID) ON DELETE CASCADE,
    TREATMENT_ID NUMBER REFERENCES TREATMENTS(TREATMENT_ID) ON DELETE CASCADE,
    RECOVERY_SCORE NUMBER(5,2),
    SIDE_EFFECTS VARCHAR2(255),
    READMITTED_30D NUMBER(1) DEFAULT 0,
    FOLLOW_UP_DATE DATE,
    OUTCOME_NOTES VARCHAR2(500)
);

CREATE TABLE CARE_RECOMMENDATIONS (
    RECOMMENDATION_ID NUMBER PRIMARY KEY,
    PATIENT_ID NUMBER NOT NULL REFERENCES PATIENTS(PATIENT_ID) ON DELETE CASCADE,
    DOCTOR_ID NUMBER REFERENCES USERS(USER_ID),
    RISK_LEVEL VARCHAR2(20),
    CARE_PLAN_SUMMARY VARCHAR2(1000),
    FOLLOW_UP_SCHEDULE VARCHAR2(255),
    MEDICATION_ADJUSTMENT VARCHAR2(500),
    DISCHARGE_SUPPORT VARCHAR2(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE AI_MODELS (
    MODEL_ID NUMBER PRIMARY KEY,
    MODEL_NAME VARCHAR2(50) UNIQUE NOT NULL,
    ALGORITHM VARCHAR2(50) NOT NULL,
    ACCURACY NUMBER(6,4),
    PRECISION_SCORE NUMBER(6,4),
    RECALL_SCORE NUMBER(6,4),
    F1_SCORE NUMBER(6,4),
    ROC_AUC NUMBER(6,4),
    HYPERPARAMETERS VARCHAR2(1000),
    IS_PROMOTED NUMBER(1) DEFAULT 0,
    TRAINED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE DATASET_METRICS (
    METRIC_ID NUMBER PRIMARY KEY,
    DATASET_NAME VARCHAR2(100) NOT NULL,
    TOTAL_RECORDS NUMBER NOT NULL,
    TRAIN_RECORDS NUMBER NOT NULL,
    TEST_RECORDS NUMBER NOT NULL,
    NUM_FEATURES NUMBER NOT NULL,
    DECISION_THRESHOLD NUMBER(6,4),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE HOSPITAL_ANALYTICS (
    ANALYTICS_ID NUMBER PRIMARY KEY,
    REPORT_DATE DATE NOT NULL,
    TOTAL_ADMISSIONS NUMBER NOT NULL,
    READMISSION_RATE NUMBER(5,2) NOT NULL,
    HIGH_RISK_COUNT NUMBER NOT NULL,
    AVG_LENGTH_OF_STAY NUMBER(4,1),
    TREATMENT_SUCCESS_RATE NUMBER(5,2)
);

CREATE TABLE AUDIT_LOGS (
    LOG_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER REFERENCES USERS(USER_ID),
    ACTION VARCHAR2(100) NOT NULL,
    RESOURCE_NAME VARCHAR2(100),
    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DETAILS VARCHAR2(500)
);

-- SEED USERS
INSERT INTO USERS (USER_ID, FULL_NAME, EMAIL, HASHED_PASSWORD, ROLE, DEPARTMENT) VALUES (1, 'System Administrator', 'admin@healthforecast.org', '$2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeg6Lruj3vjPGga31lW', 'system_admin', 'IT & Operations');
INSERT INTO USERS (USER_ID, FULL_NAME, EMAIL, HASHED_PASSWORD, ROLE, DEPARTMENT) VALUES (2, 'Hospital Administrator', 'admin.ops@healthforecast.org', '$2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeg6Lruj3vjPGga31lW', 'hospital_admin', 'Hospital Management');
INSERT INTO USERS (USER_ID, FULL_NAME, EMAIL, HASHED_PASSWORD, ROLE, DEPARTMENT) VALUES (3, 'Dr. Rajesh Reddy', 'dr.reddy@healthforecast.org', '$2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeg6Lruj3vjPGga31lW', 'doctor', 'Endocrinology & Internal Medicine');
INSERT INTO USERS (USER_ID, FULL_NAME, EMAIL, HASHED_PASSWORD, ROLE, DEPARTMENT) VALUES (4, 'Dr. Ananya Sharma', 'dr.sharma@healthforecast.org', '$2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeg6Lruj3vjPGga31lW', 'doctor', 'Cardiology');
INSERT INTO USERS (USER_ID, FULL_NAME, EMAIL, HASHED_PASSWORD, ROLE, DEPARTMENT) VALUES (5, 'Dr. Vikram Malhotra', 'dr.malhotra@healthforecast.org', '$2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeg6Lruj3vjPGga31lW', 'doctor', 'Nephrology');
INSERT INTO USERS (USER_ID, FULL_NAME, EMAIL, HASHED_PASSWORD, ROLE, DEPARTMENT) VALUES (6, 'Healthcare Researcher', 'researcher@healthforecast.org', '$2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeg6Lruj3vjPGga31lW', 'researcher', 'Clinical Analytics & AI Research');

-- SEED PATIENTS
INSERT INTO PATIENTS (PATIENT_ID, MEDICAL_RECORD_NUMBER, FIRST_NAME, LAST_NAME, GENDER, AGE_GROUP, RACE, BLOOD_TYPE, CONTACT_NUMBER, PRIMARY_DOCTOR_ID) VALUES (1001, 'MRN-789012', 'Aarav', 'Patel', 'Male', '[60-70)', 'Caucasian', 'O+', '+1-555-0101', 3);
INSERT INTO PATIENTS (PATIENT_ID, MEDICAL_RECORD_NUMBER, FIRST_NAME, LAST_NAME, GENDER, AGE_GROUP, RACE, BLOOD_TYPE, CONTACT_NUMBER, PRIMARY_DOCTOR_ID) VALUES (1002, 'MRN-789013', 'Priya', 'Sharma', 'Female', '[70-80)', 'AfricanAmerican', 'A+', '+1-555-0102', 3);
INSERT INTO PATIENTS (PATIENT_ID, MEDICAL_RECORD_NUMBER, FIRST_NAME, LAST_NAME, GENDER, AGE_GROUP, RACE, BLOOD_TYPE, CONTACT_NUMBER, PRIMARY_DOCTOR_ID) VALUES (1003, 'MRN-789014', 'Rohan', 'Verma', 'Male', '[50-60)', 'Asian', 'B+', '+1-555-0103', 4);
INSERT INTO PATIENTS (PATIENT_ID, MEDICAL_RECORD_NUMBER, FIRST_NAME, LAST_NAME, GENDER, AGE_GROUP, RACE, BLOOD_TYPE, CONTACT_NUMBER, PRIMARY_DOCTOR_ID) VALUES (1004, 'MRN-789015', 'Sunita', 'Deshmukh', 'Female', '[80-90)', 'Caucasian', 'AB+', '+1-555-0104', 3);
INSERT INTO PATIENTS (PATIENT_ID, MEDICAL_RECORD_NUMBER, FIRST_NAME, LAST_NAME, GENDER, AGE_GROUP, RACE, BLOOD_TYPE, CONTACT_NUMBER, PRIMARY_DOCTOR_ID) VALUES (1005, 'MRN-789016', 'Karan', 'Singh', 'Male', '[40-50)', 'Hispanic', 'O-', '+1-555-0105', 5);
INSERT INTO PATIENTS (PATIENT_ID, MEDICAL_RECORD_NUMBER, FIRST_NAME, LAST_NAME, GENDER, AGE_GROUP, RACE, BLOOD_TYPE, CONTACT_NUMBER, PRIMARY_DOCTOR_ID) VALUES (1006, 'MRN-789017', 'Meera', 'Nair', 'Female', '[60-70)', 'Other', 'A-', '+1-555-0106', 4);
INSERT INTO PATIENTS (PATIENT_ID, MEDICAL_RECORD_NUMBER, FIRST_NAME, LAST_NAME, GENDER, AGE_GROUP, RACE, BLOOD_TYPE, CONTACT_NUMBER, PRIMARY_DOCTOR_ID) VALUES (1007, 'MRN-789018', 'Vikram', 'Joshi', 'Male', '[70-80)', 'Caucasian', 'B-', '+1-555-0107', 3);
INSERT INTO PATIENTS (PATIENT_ID, MEDICAL_RECORD_NUMBER, FIRST_NAME, LAST_NAME, GENDER, AGE_GROUP, RACE, BLOOD_TYPE, CONTACT_NUMBER, PRIMARY_DOCTOR_ID) VALUES (1008, 'MRN-789019', 'Neha', 'Gupta', 'Female', '[50-60)', 'AfricanAmerican', 'O+', '+1-555-0108', 5);

-- SEED MEDICAL HISTORIES
INSERT INTO MEDICAL_HISTORIES (HISTORY_ID, PATIENT_ID, PRIMARY_DIAGNOSIS, SECONDARY_DIAGNOSIS, ADDITIONAL_DIAGNOSIS, COMORBIDITIES_COUNT, ADMISSION_TYPE, NUM_LAB_PROCEDURES, NUM_PROCEDURES, NUM_MEDICATIONS, NUMBER_OUTPATIENT, NUMBER_EMERGENCY, NUMBER_INPATIENT, TIME_IN_HOSPITAL, ADMISSION_DATE, DISCHARGE_DATE) VALUES (5001, 1001, 'Diabetes mellitus with renal manifestations (ICD 250.4)', 'Hypertensive chronic kidney disease (ICD 403)', 'Hyperlipidemia (ICD 272.4)', 4, 'Emergency', 68, 3, 18, 1, 2, 3, 7, TO_DATE('2026-08-01', 'YYYY-MM-DD'), TO_DATE('2026-08-08', 'YYYY-MM-DD'));
INSERT INTO MEDICAL_HISTORIES (HISTORY_ID, PATIENT_ID, PRIMARY_DIAGNOSIS, SECONDARY_DIAGNOSIS, ADDITIONAL_DIAGNOSIS, COMORBIDITIES_COUNT, ADMISSION_TYPE, NUM_LAB_PROCEDURES, NUM_PROCEDURES, NUM_MEDICATIONS, NUMBER_OUTPATIENT, NUMBER_EMERGENCY, NUMBER_INPATIENT, TIME_IN_HOSPITAL, ADMISSION_DATE, DISCHARGE_DATE) VALUES (5002, 1002, 'Type 2 diabetes with neurological complications (ICD 250.6)', 'Coronary atherosclerosis (ICD 414.0)', 'Congestive heart failure (ICD 428.0)', 5, 'Urgent', 74, 4, 22, 2, 1, 4, 9, TO_DATE('2026-08-05', 'YYYY-MM-DD'), TO_DATE('2026-08-14', 'YYYY-MM-DD'));
INSERT INTO MEDICAL_HISTORIES (HISTORY_ID, PATIENT_ID, PRIMARY_DIAGNOSIS, SECONDARY_DIAGNOSIS, ADDITIONAL_DIAGNOSIS, COMORBIDITIES_COUNT, ADMISSION_TYPE, NUM_LAB_PROCEDURES, NUM_PROCEDURES, NUM_MEDICATIONS, NUMBER_OUTPATIENT, NUMBER_EMERGENCY, NUMBER_INPATIENT, TIME_IN_HOSPITAL, ADMISSION_DATE, DISCHARGE_DATE) VALUES (5003, 1003, 'Uncontrolled Type 2 Diabetes Mellitus (ICD 250.02)', 'Essential primary hypertension (ICD 401.9)', 'None', 2, 'Elective', 42, 1, 12, 0, 0, 1, 3, TO_DATE('2026-08-10', 'YYYY-MM-DD'), TO_DATE('2026-08-13', 'YYYY-MM-DD'));
INSERT INTO MEDICAL_HISTORIES (HISTORY_ID, PATIENT_ID, PRIMARY_DIAGNOSIS, SECONDARY_DIAGNOSIS, ADDITIONAL_DIAGNOSIS, COMORBIDITIES_COUNT, ADMISSION_TYPE, NUM_LAB_PROCEDURES, NUM_PROCEDURES, NUM_MEDICATIONS, NUMBER_OUTPATIENT, NUMBER_EMERGENCY, NUMBER_INPATIENT, TIME_IN_HOSPITAL, ADMISSION_DATE, DISCHARGE_DATE) VALUES (5004, 1004, 'Diabetic ketoacidosis (ICD 250.13)', 'Acute kidney failure (ICD 584.9)', 'Atrial fibrillation (ICD 427.31)', 6, 'Emergency', 85, 5, 26, 3, 4, 5, 12, TO_DATE('2026-08-12', 'YYYY-MM-DD'), TO_DATE('2026-08-24', 'YYYY-MM-DD'));
INSERT INTO MEDICAL_HISTORIES (HISTORY_ID, PATIENT_ID, PRIMARY_DIAGNOSIS, SECONDARY_DIAGNOSIS, ADDITIONAL_DIAGNOSIS, COMORBIDITIES_COUNT, ADMISSION_TYPE, NUM_LAB_PROCEDURES, NUM_PROCEDURES, NUM_MEDICATIONS, NUMBER_OUTPATIENT, NUMBER_EMERGENCY, NUMBER_INPATIENT, TIME_IN_HOSPITAL, ADMISSION_DATE, DISCHARGE_DATE) VALUES (5005, 1005, 'Diabetes mellitus with ophthalmic manifestations (ICD 250.5)', 'Obesity (ICD 278.0)', 'Asthma (ICD 493.9)', 3, 'Urgent', 51, 2, 14, 1, 0, 2, 5, TO_DATE('2026-08-15', 'YYYY-MM-DD'), TO_DATE('2026-08-20', 'YYYY-MM-DD'));
INSERT INTO MEDICAL_HISTORIES (HISTORY_ID, PATIENT_ID, PRIMARY_DIAGNOSIS, SECONDARY_DIAGNOSIS, ADDITIONAL_DIAGNOSIS, COMORBIDITIES_COUNT, ADMISSION_TYPE, NUM_LAB_PROCEDURES, NUM_PROCEDURES, NUM_MEDICATIONS, NUMBER_OUTPATIENT, NUMBER_EMERGENCY, NUMBER_INPATIENT, TIME_IN_HOSPITAL, ADMISSION_DATE, DISCHARGE_DATE) VALUES (5006, 1006, 'Type 2 diabetes mellitus without complications (ICD 250.00)', 'Osteoarthritis (ICD 715.9)', 'None', 1, 'Elective', 38, 1, 9, 0, 0, 1, 2, TO_DATE('2026-08-18', 'YYYY-MM-DD'), TO_DATE('2026-08-20', 'YYYY-MM-DD'));
INSERT INTO MEDICAL_HISTORIES (HISTORY_ID, PATIENT_ID, PRIMARY_DIAGNOSIS, SECONDARY_DIAGNOSIS, ADDITIONAL_DIAGNOSIS, COMORBIDITIES_COUNT, ADMISSION_TYPE, NUM_LAB_PROCEDURES, NUM_PROCEDURES, NUM_MEDICATIONS, NUMBER_OUTPATIENT, NUMBER_EMERGENCY, NUMBER_INPATIENT, TIME_IN_HOSPITAL, ADMISSION_DATE, DISCHARGE_DATE) VALUES (5007, 1007, 'Diabetic peripheral angiopathy (ICD 250.7)', 'Peripheral vascular disease (ICD 443.9)', 'Hypertension (ICD 401.9)', 4, 'Emergency', 62, 3, 19, 2, 1, 3, 8, TO_DATE('2026-08-22', 'YYYY-MM-DD'), TO_DATE('2026-08-30', 'YYYY-MM-DD'));
INSERT INTO MEDICAL_HISTORIES (HISTORY_ID, PATIENT_ID, PRIMARY_DIAGNOSIS, SECONDARY_DIAGNOSIS, ADDITIONAL_DIAGNOSIS, COMORBIDITIES_COUNT, ADMISSION_TYPE, NUM_LAB_PROCEDURES, NUM_PROCEDURES, NUM_MEDICATIONS, NUMBER_OUTPATIENT, NUMBER_EMERGENCY, NUMBER_INPATIENT, TIME_IN_HOSPITAL, ADMISSION_DATE, DISCHARGE_DATE) VALUES (5008, 1008, 'Type 2 diabetes with hypoglycemia (ICD 250.8)', 'Major depressive disorder (ICD 296.2)', 'Hypothyroidism (ICD 244.9)', 3, 'Emergency', 49, 2, 15, 1, 1, 2, 4, TO_DATE('2026-08-25', 'YYYY-MM-DD'), TO_DATE('2026-08-29', 'YYYY-MM-DD'));

-- SEED READMISSION PREDICTIONS
INSERT INTO READMISSION_PREDICTIONS (PREDICTION_ID, PATIENT_ID, MODEL_NAME, READMISSION_RISK_SCORE, RISK_CATEGORY, PREDICTED_READMIT_30D, CONFIDENCE_INTERVAL) VALUES (8001, 1001, 'Random Forest Classifier', 0.815, 'HIGH', 1, '95% CI (0.76 - 0.86)');
INSERT INTO READMISSION_PREDICTIONS (PREDICTION_ID, PATIENT_ID, MODEL_NAME, READMISSION_RISK_SCORE, RISK_CATEGORY, PREDICTED_READMIT_30D, CONFIDENCE_INTERVAL) VALUES (8002, 1002, 'XGBoost Classifier', 0.882, 'HIGH', 1, '95% CI (0.83 - 0.92)');
INSERT INTO READMISSION_PREDICTIONS (PREDICTION_ID, PATIENT_ID, MODEL_NAME, READMISSION_RISK_SCORE, RISK_CATEGORY, PREDICTED_READMIT_30D, CONFIDENCE_INTERVAL) VALUES (8003, 1003, 'Random Forest Classifier', 0.241, 'LOW', 0, '95% CI (0.19 - 0.29)');
INSERT INTO READMISSION_PREDICTIONS (PREDICTION_ID, PATIENT_ID, MODEL_NAME, READMISSION_RISK_SCORE, RISK_CATEGORY, PREDICTED_READMIT_30D, CONFIDENCE_INTERVAL) VALUES (8004, 1004, 'XGBoost Classifier', 0.914, 'HIGH', 1, '95% CI (0.87 - 0.95)');
INSERT INTO READMISSION_PREDICTIONS (PREDICTION_ID, PATIENT_ID, MODEL_NAME, READMISSION_RISK_SCORE, RISK_CATEGORY, PREDICTED_READMIT_30D, CONFIDENCE_INTERVAL) VALUES (8005, 1005, 'Random Forest Classifier', 0.485, 'MEDIUM', 0, '95% CI (0.42 - 0.54)');
INSERT INTO READMISSION_PREDICTIONS (PREDICTION_ID, PATIENT_ID, MODEL_NAME, READMISSION_RISK_SCORE, RISK_CATEGORY, PREDICTED_READMIT_30D, CONFIDENCE_INTERVAL) VALUES (8006, 1006, 'Random Forest Classifier', 0.182, 'LOW', 0, '95% CI (0.13 - 0.23)');
INSERT INTO READMISSION_PREDICTIONS (PREDICTION_ID, PATIENT_ID, MODEL_NAME, READMISSION_RISK_SCORE, RISK_CATEGORY, PREDICTED_READMIT_30D, CONFIDENCE_INTERVAL) VALUES (8007, 1007, 'XGBoost Classifier', 0.764, 'HIGH', 1, '95% CI (0.71 - 0.81)');
INSERT INTO READMISSION_PREDICTIONS (PREDICTION_ID, PATIENT_ID, MODEL_NAME, READMISSION_RISK_SCORE, RISK_CATEGORY, PREDICTED_READMIT_30D, CONFIDENCE_INTERVAL) VALUES (8008, 1008, 'Random Forest Classifier', 0.395, 'MEDIUM', 0, '95% CI (0.33 - 0.45)');

-- SEED TREATMENTS
INSERT INTO TREATMENTS (TREATMENT_ID, PATIENT_ID, MEDICATION_NAME, DOSAGE, FREQUENCY, START_DATE, END_DATE, EFFECTIVENESS_SCORE, STATUS) VALUES (3001, 1001, 'Metformin + Insulin Glargine', '1000mg / 20 units', 'Twice daily', TO_DATE('2026-08-08', 'YYYY-MM-DD'), TO_DATE('2026-09-08', 'YYYY-MM-DD'), 84.5, 'ACTIVE');
INSERT INTO TREATMENTS (TREATMENT_ID, PATIENT_ID, MEDICATION_NAME, DOSAGE, FREQUENCY, START_DATE, END_DATE, EFFECTIVENESS_SCORE, STATUS) VALUES (3002, 1002, 'Insulin Lispro + Empagliflozin', '15 units / 10mg', 'Three times daily', TO_DATE('2026-08-14', 'YYYY-MM-DD'), TO_DATE('2026-09-14', 'YYYY-MM-DD'), 78.2, 'ACTIVE');
INSERT INTO TREATMENTS (TREATMENT_ID, PATIENT_ID, MEDICATION_NAME, DOSAGE, FREQUENCY, START_DATE, END_DATE, EFFECTIVENESS_SCORE, STATUS) VALUES (3003, 1003, 'Metformin HCl', '500mg', 'Twice daily', TO_DATE('2026-08-13', 'YYYY-MM-DD'), TO_DATE('2026-11-13', 'YYYY-MM-DD'), 92.0, 'ACTIVE');
INSERT INTO TREATMENTS (TREATMENT_ID, PATIENT_ID, MEDICATION_NAME, DOSAGE, FREQUENCY, START_DATE, END_DATE, EFFECTIVENESS_SCORE, STATUS) VALUES (3004, 1004, 'Insulin Regular + Sitagliptin', '25 units / 100mg', 'Four times daily', TO_DATE('2026-08-24', 'YYYY-MM-DD'), TO_DATE('2026-09-24', 'YYYY-MM-DD'), 69.5, 'ACTIVE');
INSERT INTO TREATMENTS (TREATMENT_ID, PATIENT_ID, MEDICATION_NAME, DOSAGE, FREQUENCY, START_DATE, END_DATE, EFFECTIVENESS_SCORE, STATUS) VALUES (3005, 1005, 'Glipizide XL', '5mg', 'Once daily', TO_DATE('2026-08-20', 'YYYY-MM-DD'), TO_DATE('2026-10-20', 'YYYY-MM-DD'), 88.0, 'ACTIVE');
INSERT INTO TREATMENTS (TREATMENT_ID, PATIENT_ID, MEDICATION_NAME, DOSAGE, FREQUENCY, START_DATE, END_DATE, EFFECTIVENESS_SCORE, STATUS) VALUES (3006, 1006, 'Metformin XR', '850mg', 'Once daily', TO_DATE('2026-08-20', 'YYYY-MM-DD'), TO_DATE('2026-11-20', 'YYYY-MM-DD'), 95.0, 'ACTIVE');
INSERT INTO TREATMENTS (TREATMENT_ID, PATIENT_ID, MEDICATION_NAME, DOSAGE, FREQUENCY, START_DATE, END_DATE, EFFECTIVENESS_SCORE, STATUS) VALUES (3007, 1007, 'Insulin Glargine + Pioglitazone', '30 units / 15mg', 'Twice daily', TO_DATE('2026-08-30', 'YYYY-MM-DD'), TO_DATE('2026-09-30', 'YYYY-MM-DD'), 81.0, 'ACTIVE');
INSERT INTO TREATMENTS (TREATMENT_ID, PATIENT_ID, MEDICATION_NAME, DOSAGE, FREQUENCY, START_DATE, END_DATE, EFFECTIVENESS_SCORE, STATUS) VALUES (3008, 1008, 'Liraglutide (Victoza)', '1.2mg injection', 'Once daily', TO_DATE('2026-08-29', 'YYYY-MM-DD'), TO_DATE('2026-09-29', 'YYYY-MM-DD'), 86.5, 'ACTIVE');

-- SEED RECOVERY MONITORING
INSERT INTO RECOVERY_MONITORING (OUTCOME_ID, PATIENT_ID, TREATMENT_ID, RECOVERY_SCORE, SIDE_EFFECTS, READMITTED_30D, FOLLOW_UP_DATE, OUTCOME_NOTES) VALUES (4001, 1001, 3001, 82.0, 'Mild nausea, controlled HbA1c', 0, TO_DATE('2026-09-15', 'YYYY-MM-DD'), 'HbA1c decreased from 9.2% to 7.8%. Blood pressure stabilized.');
INSERT INTO RECOVERY_MONITORING (OUTCOME_ID, PATIENT_ID, TREATMENT_ID, RECOVERY_SCORE, SIDE_EFFECTS, READMITTED_30D, FOLLOW_UP_DATE, OUTCOME_NOTES) VALUES (4002, 1002, 3002, 74.5, 'Occasional hypoglycemia episodes', 1, TO_DATE('2026-09-10', 'YYYY-MM-DD'), 'Readmitted due to heart failure exacerbation; insulin dosage adjusted.');
INSERT INTO RECOVERY_MONITORING (OUTCOME_ID, PATIENT_ID, TREATMENT_ID, RECOVERY_SCORE, SIDE_EFFECTS, READMITTED_30D, FOLLOW_UP_DATE, OUTCOME_NOTES) VALUES (4003, 1003, 3003, 94.0, 'None reported', 0, TO_DATE('2026-09-20', 'YYYY-MM-DD'), 'Excellent glycemic control. Glucose levels within target 110-130 mg/dL.');
INSERT INTO RECOVERY_MONITORING (OUTCOME_ID, PATIENT_ID, TREATMENT_ID, RECOVERY_SCORE, SIDE_EFFECTS, READMITTED_30D, FOLLOW_UP_DATE, OUTCOME_NOTES) VALUES (4004, 1004, 3004, 68.0, 'Renal clearance monitoring required', 1, TO_DATE('2026-09-05', 'YYYY-MM-DD'), 'High risk readmission within 18 days; transition care team assigned.');
INSERT INTO RECOVERY_MONITORING (OUTCOME_ID, PATIENT_ID, TREATMENT_ID, RECOVERY_SCORE, SIDE_EFFECTS, READMITTED_30D, FOLLOW_UP_DATE, OUTCOME_NOTES) VALUES (4005, 1005, 3005, 89.0, 'Mild dizziness in morning', 0, TO_DATE('2026-09-18', 'YYYY-MM-DD'), 'Patient compliant with diet and medication routine.');
INSERT INTO RECOVERY_MONITORING (OUTCOME_ID, PATIENT_ID, TREATMENT_ID, RECOVERY_SCORE, SIDE_EFFECTS, READMITTED_30D, FOLLOW_UP_DATE, OUTCOME_NOTES) VALUES (4006, 1006, 3006, 96.0, 'None', 0, TO_DATE('2026-09-25', 'YYYY-MM-DD'), 'Complete symptom resolution. Normal fasting blood glucose.');
INSERT INTO RECOVERY_MONITORING (OUTCOME_ID, PATIENT_ID, TREATMENT_ID, RECOVERY_SCORE, SIDE_EFFECTS, READMITTED_30D, FOLLOW_UP_DATE, OUTCOME_NOTES) VALUES (4007, 1007, 3007, 79.0, 'Mild peripheral edema', 0, TO_DATE('2026-09-12', 'YYYY-MM-DD'), 'Wound healing progressing following vascular consult.');
INSERT INTO RECOVERY_MONITORING (OUTCOME_ID, PATIENT_ID, TREATMENT_ID, RECOVERY_SCORE, SIDE_EFFECTS, READMITTED_30D, FOLLOW_UP_DATE, OUTCOME_NOTES) VALUES (4008, 1008, 3008, 87.5, 'Transient appetite suppression', 0, TO_DATE('2026-09-22', 'YYYY-MM-DD'), 'Significant improvement in mood and glycemic stability.');

-- SEED CARE RECOMMENDATIONS
INSERT INTO CARE_RECOMMENDATIONS (RECOMMENDATION_ID, PATIENT_ID, DOCTOR_ID, RISK_LEVEL, CARE_PLAN_SUMMARY, FOLLOW_UP_SCHEDULE, MEDICATION_ADJUSTMENT, DISCHARGE_SUPPORT) VALUES (2001, 1001, 3, 'HIGH', 'Intensive 30-day post-discharge monitoring. Weekly tele-health nurse check-in.', '2026-09-15', 'Adjust Insulin Glargine to 18 units if morning glucose > 140 mg/dL.', 'Provide home blood glucose monitor and nephrology follow-up voucher.');
INSERT INTO CARE_RECOMMENDATIONS (RECOMMENDATION_ID, PATIENT_ID, DOCTOR_ID, RISK_LEVEL, CARE_PLAN_SUMMARY, FOLLOW_UP_SCHEDULE, MEDICATION_ADJUSTMENT, DISCHARGE_SUPPORT) VALUES (2002, 1002, 3, 'HIGH', 'Cardiology & Endocrinology co-management. Strict sodium and fluid restriction.', '2026-09-10', 'Hold Empagliflozin if eGFR drops below 30 mL/min.', 'Home health nurse visit within 48 hours of discharge.');
INSERT INTO CARE_RECOMMENDATIONS (RECOMMENDATION_ID, PATIENT_ID, DOCTOR_ID, RISK_LEVEL, CARE_PLAN_SUMMARY, FOLLOW_UP_SCHEDULE, MEDICATION_ADJUSTMENT, DISCHARGE_SUPPORT) VALUES (2003, 1003, 4, 'LOW', 'Standard diabetes management and routine quarterly HbA1c review.', '2026-09-20', 'Maintain Metformin 500mg BID.', 'Nutritional counseling and exercise guidance provided.');
INSERT INTO CARE_RECOMMENDATIONS (RECOMMENDATION_ID, PATIENT_ID, DOCTOR_ID, RISK_LEVEL, CARE_PLAN_SUMMARY, FOLLOW_UP_SCHEDULE, MEDICATION_ADJUSTMENT, DISCHARGE_SUPPORT) VALUES (2004, 1004, 3, 'HIGH', 'High-Risk Readmission protocol. Outpatient dialysis coordination.', '2026-09-05', 'Taper regular insulin based on sliding scale.', 'Dedicated case manager appointed for medication reconciliation.');

-- SEED AI MODELS
INSERT INTO AI_MODELS (MODEL_ID, MODEL_NAME, ALGORITHM, ACCURACY, PRECISION_SCORE, RECALL_SCORE, F1_SCORE, ROC_AUC, HYPERPARAMETERS, IS_PROMOTED) VALUES (1, 'Random Forest Classifier', 'RandomForestClassifier', 0.7871, 0.745, 0.362, 0.487, 0.6512, '{"n_estimators": 250, "max_depth": 10, "min_samples_split": 10, "class_weight": "balanced", "random_state": 42}', 1);
INSERT INTO AI_MODELS (MODEL_ID, MODEL_NAME, ALGORITHM, ACCURACY, PRECISION_SCORE, RECALL_SCORE, F1_SCORE, ROC_AUC, HYPERPARAMETERS, IS_PROMOTED) VALUES (2, 'XGBoost Classifier', 'XGBClassifier', 0.7903, 0.758, 0.341, 0.471, 0.6391, '{"n_estimators": 200, "max_depth": 4, "learning_rate": 0.03, "subsample": 0.8, "scale_pos_weight": 2.5, "random_state": 42}', 0);
INSERT INTO AI_MODELS (MODEL_ID, MODEL_NAME, ALGORITHM, ACCURACY, PRECISION_SCORE, RECALL_SCORE, F1_SCORE, ROC_AUC, HYPERPARAMETERS, IS_PROMOTED) VALUES (3, 'Logistic Regression', 'LogisticRegression', 0.7883, 0.741, 0.358, 0.483, 0.6502, '{"C": 0.1, "max_iter": 1000, "solver": "lbfgs", "class_weight": "balanced", "random_state": 42}', 0);

-- SEED DATASET METRICS
INSERT INTO DATASET_METRICS (METRIC_ID, DATASET_NAME, TOTAL_RECORDS, TRAIN_RECORDS, TEST_RECORDS, NUM_FEATURES, DECISION_THRESHOLD) VALUES (1, 'Diabetes 130-US Hospitals Dataset', 101766, 81412, 20354, 42, 0.1285);

-- SEED HOSPITAL ANALYTICS
INSERT INTO HOSPITAL_ANALYTICS (ANALYTICS_ID, REPORT_DATE, TOTAL_ADMISSIONS, READMISSION_RATE, HIGH_RISK_COUNT, AVG_LENGTH_OF_STAY, TREATMENT_SUCCESS_RATE) VALUES (1, TO_DATE('2026-08-31', 'YYYY-MM-DD'), 1250, 11.2, 142, 4.8, 88.5);
INSERT INTO HOSPITAL_ANALYTICS (ANALYTICS_ID, REPORT_DATE, TOTAL_ADMISSIONS, READMISSION_RATE, HIGH_RISK_COUNT, AVG_LENGTH_OF_STAY, TREATMENT_SUCCESS_RATE) VALUES (2, TO_DATE('2026-07-31', 'YYYY-MM-DD'), 1190, 11.8, 155, 5.1, 86.2);
INSERT INTO HOSPITAL_ANALYTICS (ANALYTICS_ID, REPORT_DATE, TOTAL_ADMISSIONS, READMISSION_RATE, HIGH_RISK_COUNT, AVG_LENGTH_OF_STAY, TREATMENT_SUCCESS_RATE) VALUES (3, TO_DATE('2026-06-30', 'YYYY-MM-DD'), 1310, 12.1, 168, 5.0, 85.7);
INSERT INTO HOSPITAL_ANALYTICS (ANALYTICS_ID, REPORT_DATE, TOTAL_ADMISSIONS, READMISSION_RATE, HIGH_RISK_COUNT, AVG_LENGTH_OF_STAY, TREATMENT_SUCCESS_RATE) VALUES (4, TO_DATE('2026-05-31', 'YYYY-MM-DD'), 1280, 12.5, 174, 5.3, 84.9);

-- SEED AUDIT LOGS
INSERT INTO AUDIT_LOGS (LOG_ID, USER_ID, ACTION, RESOURCE_NAME, DETAILS) VALUES (1, 1, 'USER_LOGIN', 'AUTH_SERVICE', 'System Administrator logged in successfully.');
INSERT INTO AUDIT_LOGS (LOG_ID, USER_ID, ACTION, RESOURCE_NAME, DETAILS) VALUES (2, 3, 'VIEW_PATIENT_RECORD', 'PATIENT_1001', 'Dr. Rajesh Reddy accessed medical history for Aarav Patel.');
INSERT INTO AUDIT_LOGS (LOG_ID, USER_ID, ACTION, RESOURCE_NAME, DETAILS) VALUES (3, 1, 'MODEL_RETRAIN', 'RANDOM_FOREST', 'Model retrained on 101,766 records. Test accuracy: 78.71%.');
INSERT INTO AUDIT_LOGS (LOG_ID, USER_ID, ACTION, RESOURCE_NAME, DETAILS) VALUES (4, 2, 'GENERATE_REPORT', 'HOSPITAL_ANALYTICS', 'Hospital Administrator generated monthly readmission performance report.');

COMMIT;
PROMPT --- HEALTHFORECAST AI ORACLE DATABASE SETUP COMPLETED ---
EXIT;