SET PAGESIZE 100;
SET LINESIZE 200;
SELECT table_name FROM user_tables ORDER BY table_name;
SELECT 'USERS' AS TBL, COUNT(*) AS CNT FROM USERS
UNION ALL SELECT 'PATIENTS', COUNT(*) FROM PATIENTS
UNION ALL SELECT 'MEDICAL_HISTORIES', COUNT(*) FROM MEDICAL_HISTORIES
UNION ALL SELECT 'READMISSION_PREDICTIONS', COUNT(*) FROM READMISSION_PREDICTIONS
UNION ALL SELECT 'TREATMENTS', COUNT(*) FROM TREATMENTS
UNION ALL SELECT 'RECOVERY_MONITORING', COUNT(*) FROM RECOVERY_MONITORING
UNION ALL SELECT 'CARE_RECOMMENDATIONS', COUNT(*) FROM CARE_RECOMMENDATIONS
UNION ALL SELECT 'AI_MODELS', COUNT(*) FROM AI_MODELS
UNION ALL SELECT 'DATASET_METRICS', COUNT(*) FROM DATASET_METRICS
UNION ALL SELECT 'HOSPITAL_ANALYTICS', COUNT(*) FROM HOSPITAL_ANALYTICS
UNION ALL SELECT 'AUDIT_LOGS', COUNT(*) FROM AUDIT_LOGS;
EXIT;
